# Generated by Django 4.2 on 2026-07-23 19:35

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
