# Generated by Django 4.2 on 2026-07-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chunk_chunk_embedding_hnsw_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('start_verse', 'end_verse', 'translation')},
        ),
    ]
